/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import models.Course;
import models.Lesson;
import jsondatabase.JsonDatabaseManager;

/**
 *
 * @author engom
 */
public class AddLesson extends javax.swing.JFrame {
    private Course course;
    private JsonDatabaseManager db = new JsonDatabaseManager();
    private Lesson tempLesson= new Lesson();

    /**
     * Creates new form AddLesson
     */
    public AddLesson() {
        initComponents();
    }
    public AddLesson(Course course){
        this.course=course;
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Close only this window
        setTitle("Adding Lesson");
        save.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLessonId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLessonTitle = new javax.swing.JTextField();
        content = new javax.swing.JLabel();
        txtContent = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        creatQuiz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Lesson ID");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Lesson Title");

        content.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        content.setText("Content");

        save.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        creatQuiz.setText("Create Quiz");
        creatQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatQuizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(creatQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLessonId)
                            .addComponent(txtLessonTitle)
                            .addComponent(txtContent, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                        .addContainerGap(57, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLessonId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLessonTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(creatQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            String lId = txtLessonId.getText().trim();
            String lTitle = txtLessonTitle.getText().trim();
            String lContent = txtContent.getText().trim();

            // Basic Validation
            if (lId.isEmpty() || lTitle.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in Lesson ID and Title.");
                return;
            }

            // Extra Safety Check: Ensure Quiz Exists (Though button should be disabled anyway)
            if (tempLesson.getQuiz() == null || tempLesson.getQuiz().getQuestions().isEmpty()) {
                JOptionPane.showMessageDialog(this, "You must create a quiz with at least 1 question!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check Duplicate ID
            for (Lesson l : course.getLessons()) {
                if (l.getLessonId().equals(lId)) {
                    JOptionPane.showMessageDialog(this, "Lesson ID '" + lId + "' already exists.");
                    return;
                }
            }

            // Finalize the Lesson Object
            tempLesson.setLessonId(lId);
            tempLesson.setTitle(lTitle);
            tempLesson.setContent(lContent);
            
            // Add to Course and Save
            course.addLesson(tempLesson);
            db.updateCourse(course);

            JOptionPane.showMessageDialog(this, "Lesson and Quiz Saved Successfully!");
            this.dispose(); 

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_saveActionPerformed

    private void creatQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatQuizActionPerformed
       String title = txtLessonTitle.getText().trim();
        if (title.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Lesson Title first.");
            return;
        }
        tempLesson.setTitle(title);
        
        // Open Quiz Editor
        QuizEditor quizWindow = new QuizEditor(tempLesson, course);
        
        // Add Listener to Enable Save Button ONLY if questions were added
        quizWindow.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                // Check if quiz has questions
                if (tempLesson.getQuiz() != null && !tempLesson.getQuiz().getQuestions().isEmpty()) {
                    save.setEnabled(true); // Enable the Save button
                    save.setToolTipText("Ready to save");
                    JOptionPane.showMessageDialog(AddLesson.this, "Quiz confirmed! You can now save the lesson.");
                } else {
                    save.setEnabled(false); // Keep disabled if they opened editor but added nothing
                    JOptionPane.showMessageDialog(AddLesson.this, "Quiz is empty. Please add at least one question.");
                }
            }
        });
        
        quizWindow.setVisible(true);
        
    }//GEN-LAST:event_creatQuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLesson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLesson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLesson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLesson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLesson().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel content;
    private javax.swing.JButton creatQuiz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton save;
    private javax.swing.JTextField txtContent;
    private javax.swing.JTextField txtLessonId;
    private javax.swing.JTextField txtLessonTitle;
    // End of variables declaration//GEN-END:variables
}
