/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;
import jsondatabase.JsonDatabaseManager;
import models.Course;
import models.Student;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author SHIKO
 */
public class AvailableCourses extends javax.swing.JFrame {
    
    private Student loggedStudent;
    private JTable tableAvailable;
    private DefaultTableModel tableModel;
    private JsonDatabaseManager db = new JsonDatabaseManager();
    public AvailableCourses() {
      this(null);
    }
    public AvailableCourses(Student student) {
           this.loggedStudent = student;

    initComponents(); 
        setLocationRelativeTo(null);
    tableModel = new DefaultTableModel(
        new Object[]{"Course ID", "Title", "Instructor"}, 0
    );
    jTable1.setModel(tableModel);

    loadAvailableCourses();     
    }
   private void loadAvailableCourses() {
    tableModel.setRowCount(0); // Clear existing rows
    
    List<Course> allCourses = db.loadCourses();
    
    // Get student's enrolled course IDs
    List<String> enrolledIds = loggedStudent.getEnrolledCourdseIds();
    
    for (Course c : allCourses) {
        // Only show APPROVED courses
        if (!"APPROVED".equals(c.getStatus())) {
            continue; // Skip non-approved courses
        }
        
        // Only show courses the student is NOT already enrolled in
        if (enrolledIds.contains(c.getCourseId())) {
            continue; // Skip already enrolled courses
        }
        
        // Add to table (this course is available for enrollment)
        tableModel.addRow(new Object[]{
            c.getCourseId(),
            c.getTitle(),
            c.getInstructorId()
        });
    }
    
    // Update message
    if (tableModel.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this,
            "No available courses to enroll in.\nYou may be enrolled in all courses already!",
            "No Courses",
            JOptionPane.INFORMATION_MESSAGE);
    }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course ID", "Title", "Instructor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Enroll");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("Available Courses");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addGap(231, 231, 231)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            int selectedRow = jTable1.getSelectedRow(); // Replace 'table' with your actual table variable name
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this,
            "Please select a course to enroll.",
            "No Selection",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Get course ID from selected row
    String courseId = tableModel.getValueAt(selectedRow, 0).toString();
    
    // Check if already enrolled (shouldn't happen, but double-check)
    if (loggedStudent.getEnrolledCourdseIds().contains(courseId)) {
        JOptionPane.showMessageDialog(this,
            "You are already enrolled in this course!",
            "Already Enrolled",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Get course object
    Course course = db.getCourseById(courseId);
    
    if (course == null) {
        JOptionPane.showMessageDialog(this,
            "Error: Course not found!",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Enroll student in course
    loggedStudent.enrollInCourse(courseId);
    
    // Add student to course's student list
    course.getStudents().add(String.valueOf(loggedStudent.getUserId()));
    
    // Save changes to database
    db.updateUser(loggedStudent);
    db.updateCourse(course);
    
    JOptionPane.showMessageDialog(this,
        "Successfully enrolled in: " + course.getTitle(),
        "Enrollment Success",
        JOptionPane.INFORMATION_MESSAGE);
    
    // Refresh the table (remove enrolled course from available)
    loadAvailableCourses(); // Refresh table
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new StudentDashboard(loggedStudent).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvailableCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvailableCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvailableCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvailableCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvailableCourses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
