/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;
import jsondatabase.JsonDatabaseManager;
import models.Course;
import models.Student;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import models.User;

/**
 *
 * @author engom
 */
public class EnrolledStudents extends javax.swing.JFrame {
    private Course course;
    private DefaultTableModel tableModel;
    private JsonDatabaseManager db = new JsonDatabaseManager();

    /**
     * Creates new form EnrolledStudents
     */
    public EnrolledStudents() {
        initComponents();
    }
    public EnrolledStudents(Course course) {
        this.course = course;
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Close only this window
        
        // Set Title
        
        loadStudents();
    }
    private void loadStudents() {
    // 1. Initialize the Table Model FIRST
    String[] colNames = {"Name", "ID", "Email"};
    tableModel = new DefaultTableModel(colNames, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Make read-only
        }
    };

    // 2. Safety Check
    if (course == null) return;

    // 3. Get Student IDs
    java.util.List<String> studentIds = course.getStudents();

    // 🔹 Set to avoid duplicates
    java.util.Set<Integer> seenIds = new java.util.HashSet<>();

    if (studentIds != null && !studentIds.isEmpty()) {
        // Load users to find matches
        java.util.List<User> allUsers = db.loadUsers();

        for (String idStr : studentIds) {
            try {
                int studentId = Integer.parseInt(idStr);

                // ✅ Skip if already added
                if (seenIds.contains(studentId)) {
                    continue;
                }

                // Find the user object
                for (User u : allUsers) {
                    if (u.getUserId() == studentId) {
                        tableModel.addRow(new Object[]{
                                u.getUsername(),
                                u.getUserId(),
                                u.getEmail()
                        });

                        // mark as seen so we don't add again
                        seenIds.add(studentId);
                        break;
                    }
                }
            } catch (NumberFormatException e) {
                System.out.println("Skipping invalid ID: " + idStr);
            }
        }
    }

    // 4. Link the model to the table (NetBeans name is jTable1)
    jTable1.setModel(tableModel);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "ID", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnrolledStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnrolledStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnrolledStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnrolledStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnrolledStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
