/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;


import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import models.Course;
import models.Lesson;
import models.Quiz;
import models.Student;

/**
 *
 * @author SHIKO
 */
public class Lessons extends javax.swing.JFrame {

    private Student loggedStudent;
    private Course course;
    private List<String> viewedLessons = new ArrayList<>();
    public Lessons() {
        
    }
    public Lessons(Student student, Course course) {
        this.loggedStudent = student;
        this.course = course;
        
        initComponents();  // NetBeans generated method
        
        // Set the course title to the label
        lblCourseTitle.setText(course.getTitle());
        lblCourseTitle.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));

        
        setLocationRelativeTo(null);  // Center the frame
        setTitle("Course Lessons");    // Window title
        
        loadLessons();  // Load lessons into table
    }
     private void loadLessons() {
        // Your code to populate the lessons table
        List<Lesson> lessons = course.getLessons();
        
        // Create table model and populate
        DefaultTableModel model = (DefaultTableModel) tableLessons.getModel();
        model.setRowCount(0);  // Clear existing rows
        
        for (Lesson lesson : lessons) {
            String status = loggedStudent.getCompletedLesssonIds().contains(lesson.getLessonId()) 
                            ? "Completed" : "Not Started";
            
            model.addRow(new Object[] {
                lesson.getLessonId(),
                lesson.getTitle(),
                status,
                "Not Taken"  // Quiz status (for Lab 8)
            });
        }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLessons = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblCourseTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("Lessons of");

        tableLessons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Lesson ID", "Title ", "Status", "Quiz Status"
            }
        ));
        jScrollPane1.setViewportView(tableLessons);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Take Quiz");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("View Content");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblCourseTitle.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblCourseTitle.setText("Course Title");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCourseTitle)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(146, 146, 146)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCourseTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    System.out.println("View Content button clicked!"); // Debug
    
    int selectedRow = tableLessons.getSelectedRow();
    System.out.println("Selected row: " + selectedRow); // Debug
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a lesson first!", 
                                      "No Selection", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Get lesson details from table
    String lessonId = tableLessons.getValueAt(selectedRow, 0).toString();
    String lessonTitle = tableLessons.getValueAt(selectedRow, 1).toString();
    
    System.out.println("Lesson ID: " + lessonId); // Debug
    System.out.println("Lesson Title: " + lessonTitle); // Debug
    
    // Find the full lesson object
    Lesson selectedLesson = null;
    for (Lesson l : course.getLessons()) {
        if (l.getLessonId().equals(lessonId)) {
            selectedLesson = l;
            break;
        }
    }
    
    if (selectedLesson == null) {
        System.out.println("ERROR: Selected lesson is null!"); // Debug
        JOptionPane.showMessageDialog(this, "Error: Lesson not found!", 
                                      "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    System.out.println("Opening LessonContent window..."); // Debug
    System.out.println("Lesson content: " + selectedLesson.getContent()); // Debug
    
    // Open content viewer
    new LessonContent(loggedStudent, course, selectedLesson).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     int selectedRow = tableLessons.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, 
            "Please select a lesson first!", 
            "No Selection", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Get lesson ID from table
    String lessonId = tableLessons.getValueAt(selectedRow, 0).toString();
    
    // Check if content was viewed
    if (!hasViewedContent(lessonId)) {
        JOptionPane.showMessageDialog(this, 
            "Please view the lesson content first!", 
            "Content Not Viewed", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Find the lesson object
    Lesson selectedLesson = null;
    for (Lesson l : course.getLessons()) {
        if (l.getLessonId().equals(lessonId)) {
            selectedLesson = l;
            break;
        }
    }
    
    // Verify lesson was found
    if (selectedLesson == null) {
        JOptionPane.showMessageDialog(this,
            "Error: Lesson not found!",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // ===== FIX: Check if lesson has a quiz =====
    Quiz quiz = selectedLesson.getQuiz();
    
    if (quiz == null) {
        JOptionPane.showMessageDialog(this,
            "This lesson does not have a quiz yet.\n" +
            "Please contact your instructor.",
            "No Quiz Available",
            JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    // Check if quiz has questions
    if (quiz.getQuestions() == null || quiz.getQuestions().isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "This quiz has no questions yet.\n" +
            "Please contact your instructor.",
            "No Questions Available",
            JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    // ===== Quiz exists - open QuizPage =====
    new QuizPage(loggedStudent, course, selectedLesson).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         new EnrolledCourses(loggedStudent).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

      // Helper method to check if content was viewed
private boolean hasViewedContent(String lessonId) {
    return viewedLessons.contains(lessonId);
}

// Method to mark lesson as viewed
public void markLessonViewed(String lessonId) {
    if (!viewedLessons.contains(lessonId)) {
        viewedLessons.add(lessonId);
    }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lessons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lessons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lessons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lessons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lessons().setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseTitle;
    private javax.swing.JTable tableLessons;
    // End of variables declaration//GEN-END:variables
}
