/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.lang.reflect.Method;
import java.time.Instant;
import java.util.List;
import jsondatabase.JsonDatabaseManager;
import models.Course;
import models.Admin;

/**
 *
 * @author Mizoo
 */
public class PendingCoursesss extends javax.swing.JFrame {

    private Admin loggedAdmin;
    private DefaultTableModel tableModel;
    private JsonDatabaseManager db = new JsonDatabaseManager();

    // Constructor receiving the Admin user
    public PendingCoursesss(Admin admin) {
        initComponents();      // generated UI
        this.loggedAdmin = admin;
        this.db = new JsonDatabaseManager(); // ensure DB manager is initialized
        setLocationRelativeTo(null); // center window
        initCustom();          // set up table model and listeners
        loadPendingCourses();  // populate table (synchronous, light data)
    }

    // Custom initialization: read-only table model + double-click view
    private void initCustom() {
        tableModel = new DefaultTableModel(new Object[]{"Courses ID", "Title", "Instructor"}, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        jTable1.setModel(tableModel);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // double-click row to view details
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                }
            }
        });
    }

    // Load only PENDING courses into the table
    private void loadPendingCourses() {
        tableModel.setRowCount(0); // clear
        List<Course> all = null;
        try {
            // prefer method name loadCourses() but fallback to getCourses()
            try {
                all = db.loadCourses();
            } catch (Throwable t) {
                all = db.loadCourses();
            }
            if (all == null) {
                all = java.util.Collections.emptyList();
            }
        } catch (Throwable e) {
            e.printStackTrace();
            all = java.util.Collections.emptyList();
        }

        for (Course c : all) {
            String status = "";
            try {
                status = c.getStatus() == null ? "" : c.getStatus().trim();
            } catch (Throwable ignored) {
            }
            if (!"PENDING".equalsIgnoreCase(status)) {
                continue;
            }
            Object[] row = new Object[]{c.getCourseId(), c.getTitle(), c.getInstructorId()};
            tableModel.addRow(row);
        }
    }

    // Default constructor for testing
    public PendingCoursesss() {
        initComponents();
        setLocationRelativeTo(null);
        tableModel = (DefaultTableModel) jTable1.getModel();
        loadPendingCourses();
    }

    /**
     * UPDATES STATUS IN JSON
     */
    private void updateCourseStatus(String newStatus) {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course first.");
            return;
        }

        // Get Course ID from the first column
        String courseId = (String) tableModel.getValueAt(selectedRow, 0);

        // Load all courses
        List<Course> allCourses = db.loadCourses();
        boolean found = false;

        // Find and update
        for (Course c : allCourses) {
            if (c.getCourseId().equals(courseId)) {
                c.setStatus(newStatus);
                found = true;
                break;
            }
        }

        if (found) {
            db.saveCourses(allCourses); // Save to JSON
            JOptionPane.showMessageDialog(this, "Course " + newStatus);
            loadPendingCourses(); // Refresh table
        } else {
            JOptionPane.showMessageDialog(this, "Error: Course not found.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnReject = new javax.swing.JButton();
        accept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Pending Courses");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Courses ID", "Title ", "Instructor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnReject.setBackground(new java.awt.Color(255, 51, 51));
        btnReject.setForeground(new java.awt.Color(255, 255, 255));
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        accept.setBackground(new java.awt.Color(51, 204, 0));
        accept.setForeground(new java.awt.Color(255, 255, 255));
        accept.setText("Approve");
        accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnReject)
                        .addGap(18, 18, 18)
                        .addComponent(accept)
                        .addGap(0, 92, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 90, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReject)
                    .addComponent(accept))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a course first!");
            return;
        }

        String courseId = tableModel.getValueAt(row, 0).toString().trim();

        String reason = JOptionPane.showInputDialog(this, "Reason for rejection (optional):");
        if (reason == null) {
            return;
        }

        int ok = JOptionPane.showConfirmDialog(this, "Reject course " + courseId + "?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ok != JOptionPane.YES_OPTION) {
            return;
        }

        Course c = db.getCourseById(courseId);
        if (c != null) {
            c.setStatus("REJECTED");
            try {
                Method m = c.getClass().getMethod("setRejectionReason", String.class);
                m.invoke(c, reason);
            } catch (Exception ignored) {
            }
            db.updateCourse(c);        // properly saves to JSON
            tableModel.removeRow(row); // remove from table immediately
            JOptionPane.showMessageDialog(this, "Course Rejected.");
        } else {
            JOptionPane.showMessageDialog(this, "Course not found!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRejectActionPerformed

    private void acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptActionPerformed
        System.out.println("Enterrredd");
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a course first!");
            return;
        }

        String courseId = tableModel.getValueAt(row, 0).toString().trim();
        System.out.println(courseId);
        int ok = JOptionPane.showConfirmDialog(this, "Approve course " + courseId + "?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ok != JOptionPane.YES_OPTION) {
            return;
        }
        List<Course> courses = db.loadCourses();
        Course c = null;
        for (Course cr : courses) {
            if (cr.getCourseId().equals(courseId)) {
                c = cr;
                break;
            }
        }
        if (c != null) {
            System.out.println("a");
            c.setStatus("APPROVED");
            db.updateCourse(c);        // properly saves to JSON
            tableModel.removeRow(row); // remove from table immediately
            JOptionPane.showMessageDialog(this, "Course Approved!");
        } else {
            JOptionPane.showMessageDialog(this, "Course not found!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_acceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
