/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;


import javax.swing.*;
import models.*;
import jsondatabase.JsonDatabaseManager;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author SHIKO
 */
public class QuizPage extends javax.swing.JFrame {
    private Student student;
    private Course course;
    private Lesson lesson;
    private Quiz quiz;
    private int currentIndex = 0;
    private int correctCount = 0;
    private JsonDatabaseManager db = new JsonDatabaseManager(); 
    private int[] userAnswers;
    /**
     * Creates new form Quiz
     */
    public QuizPage() {
        initComponents();
    }
     public QuizPage(Student student,Course course, Lesson lesson) {
        this.student = student;
        this.course = course;
        this.lesson = lesson;
        this.quiz = lesson.getQuiz();
        setTitle("Quiz - " + lesson.getTitle());
        setSize(600, 400);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        if (this.quiz != null) {
            this.userAnswers = new int[quiz.totalQuestions()];
            for (int i = 0; i < userAnswers.length; i++) {
                userAnswers[i] = -1; 
            }}

        initComponents();
        loadQuestion(0);

        setVisible(true);
    }
     private void saveCurrentAnswer() {
        int selected = -1;
        if (optA.isSelected()) selected = 0;
        else if (optB.isSelected()) selected = 1;
        else if (optC.isSelected()) selected = 2;
        else if (optD.isSelected()) selected = 3;

        // Save selection to the array
        userAnswers[currentIndex] = selected;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestion = new javax.swing.JTextArea();
        btnNext = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        optA = new javax.swing.JRadioButton();
        optB = new javax.swing.JRadioButton();
        optC = new javax.swing.JRadioButton();
        optD = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("Quiz");

        txtQuestion.setColumns(20);
        txtQuestion.setRows(5);
        jScrollPane1.setViewportView(txtQuestion);

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        buttonGroup1.add(optA);
        optA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAActionPerformed(evt);
            }
        });

        optB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optBActionPerformed(evt);
            }
        });

        optC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCActionPerformed(evt);
            }
        });

        optD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(optA))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(optB))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(optC)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(optD)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(optA)
                .addGap(18, 18, 18)
                .addComponent(optB)
                .addGap(18, 18, 18)
                .addComponent(optC)
                .addGap(18, 18, 18)
                .addComponent(optD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
       saveCurrentAnswer(); // Save before moving!

       currentIndex++;
       if (currentIndex < quiz.totalQuestions()) {
           loadQuestion(currentIndex);
       }
    }//GEN-LAST:event_btnNextActionPerformed
private void checkAnswer() {
    int correctIndex = quiz.getQuestions()
                           .get(currentIndex)
                           .getCorrectOptionIndex();

    int selected = -1;

    if (optA.isSelected()) selected = 0;
    else if (optB.isSelected()) selected = 1;
    else if (optC.isSelected()) selected = 2;
    else if (optD.isSelected()) selected = 3;

    if (selected == correctIndex) {
        correctCount++;
    }
}
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
      saveCurrentAnswer();

        // 2. Calculate Score by looping through the ARRAY (not the screen)
        int calculatedCorrectCount = 0;
        int total = quiz.totalQuestions();
        java.util.List<Question> questions = quiz.getQuestions();

        for (int i = 0; i < total; i++) {
            int usersSelection = userAnswers[i]; // What the student picked for Question i
            int correctIndex = questions.get(i).getCorrectOptionIndex(); // The real answer

            if (usersSelection == correctIndex) {
                calculatedCorrectCount++;
            }
        }

        // 3. Calculate Percentage
        int score = (total > 0) ? (calculatedCorrectCount * 100) / total : 0;

        // 4. Show Result
        JOptionPane.showMessageDialog(this,
            "Quiz Completed!\nCorrect: " + calculatedCorrectCount + "/" + total +
            "\nScore: " + score + "%",
            "Quiz Result",
            JOptionPane.INFORMATION_MESSAGE
        );

        // 5. Create Attempt Object
        QuizAttempt attempt = new QuizAttempt(
            lesson.getLessonId(),
            System.currentTimeMillis(),
            score,
            calculatedCorrectCount,
            total
        );

        // 6. Update Memory
        student.addQuizAttempt(lesson.getLessonId(), attempt);

        // 7. Check Passing
        boolean passed = (score >= quiz.getPassingPercentage());
        if (passed) {
            student.markLessonCompleted(lesson.getLessonId());
        }

        // 8. Save to Database (Save entire student object to persist attempts + completion)
        db.updateUser(student);

        // 9. Extra Feedback
        if (passed) {
            JOptionPane.showMessageDialog(this,
                "Congratulations! You passed this lesson.",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                "You Failed. Required: " + quiz.getPassingPercentage() + "%",
                "Failed",
                JOptionPane.WARNING_MESSAGE);
        }
           
        this.dispose();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void optAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAActionPerformed
        optionSelectedActionPerformed(evt);
    }//GEN-LAST:event_optAActionPerformed

    private void optBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optBActionPerformed
       optionSelectedActionPerformed(evt);
    }//GEN-LAST:event_optBActionPerformed

    private void optCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCActionPerformed
       optionSelectedActionPerformed(evt);
    }//GEN-LAST:event_optCActionPerformed

    private void optDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optDActionPerformed
        optionSelectedActionPerformed(evt);
    }//GEN-LAST:event_optDActionPerformed
private void loadQuestion(int index) {
        Question q = quiz.getQuestions().get(index);

        // 1. Set Text
        txtQuestion.setText("Q" + (index + 1) + ") " + q.getQuestionText());
        optA.setText(q.getOptions().size() > 0 ? q.getOptions().get(0) : "");
        optB.setText(q.getOptions().size() > 1 ? q.getOptions().get(1) : "");
        optC.setText(q.getOptions().size() > 2 ? q.getOptions().get(2) : "");
        optD.setText(q.getOptions().size() > 3 ? q.getOptions().get(3) : "");

        // 2. Restore Previous Selection
        buttonGroup1.clearSelection(); // Clear first
        int savedAnswer = userAnswers[index];
        
        if (savedAnswer == 0) optA.setSelected(true);
        else if (savedAnswer == 1) optB.setSelected(true);
        else if (savedAnswer == 2) optC.setSelected(true);
        else if (savedAnswer == 3) optD.setSelected(true);

        // 3. Enable/Disable Buttons
        btnNext.setEnabled(index < quiz.totalQuestions() - 1);
        btnSubmit.setEnabled(index == quiz.totalQuestions() - 1);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton optA;
    private javax.swing.JRadioButton optB;
    private javax.swing.JRadioButton optC;
    private javax.swing.JRadioButton optD;
    private javax.swing.JTextArea txtQuestion;
    // End of variables declaration//GEN-END:variables

    private void optionSelectedActionPerformed(java.awt.event.ActionEvent evt) {
        btnNext.setEnabled(true);

    // For the last question, enable submit
    if (currentIndex == quiz.totalQuestions() - 1) {
        btnSubmit.setEnabled(true);
    }
    }
}
